DROP DATABASE IF EXISTS exampledb;
CREATE DATABASE exampledb;

DROP DATABASE IF EXISTS testdb;
CREATE DATABASE testdb;

DROP DATABASE IF EXISTS ufo_db;
CREATE DATABASE ufo_db;

DROP DATABASE IF EXISTS bigfoot_db;
CREATE DATABASE bigfoot_db;

DROP DATABASE IF EXISTS haunted_db;
CREATE DATABASE haunted_db;
